services: 
  mariadb_apo:
    container_name: mariadb_apo
    image: mariadb
    env_file: 
      - .env    
    restart: always
    volumes:
      - /Users/apolinav/mariadb_data:/var/lib/mysql
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_PORT}:${DB_PORT}
    networks:
      - apo_red

  backend-apo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file: 
      - .env
    depends_on:
      - mariadb_apo
    links:
      - mariadb_apo
    environment:
      ENVIRONMENT_SERVER: ${ENVIRONMENT_SERVER}
      SERVER_PORT: ${APP_PORT_NEST}
      REPARTICION_SERVER: ${REPARTICION_SERVER}
      VERSION_SERVER: ${VERSION_SERVER}
      ANO_SERVER: ${ANO_SERVER}
      CREADOR_SERVER: ${CREADOR_SERVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD} 
    ports:
    - '3010:3010'
    container_name: backend-apo
    restart: always
    networks:
      - apo_red

networks:
  apo_red:

volumes:
  mariadb_apo:
  backend-apo:
    

  